import { createContext, useContext, useState } from 'react';

// ─────────────────────────────────────────────────────────────────────────────
// Translation dictionary — add a new language by adding a new key object below.
// Any missing key falls back to English automatically via the t() function.
// ─────────────────────────────────────────────────────────────────────────────
export const translations = {
  // ── ENGLISH ────────────────────────────────────────────────────────────────
  en: {
    appName: 'MediVerse', tagline: 'Smart Healthcare for Everyone',
    home: 'Home', symptomChecker: 'Symptom Checker', medicineReminder: 'Medicine Reminder',
    healthLocker: 'Health Locker', emergency: 'Emergency', settings: 'Settings',
    about: 'About', nearbyDoctors: 'Nearby Doctors',
    welcome: 'Welcome to MediVerse', welcomeSubtitle: 'Your AI-powered health companion for rural communities',
    startVoice: 'Start Voice Assistant', checkSymptoms: 'Check Symptoms',
    addReminder: 'Add Reminder', viewRecords: 'View Records', callHelp: 'Call for Help',
    online: 'Online', offline: 'Offline', syncPending: 'Sync Pending',
    save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', add: 'Add',
    yes: 'Yes', no: 'No', next: 'Next', back: 'Back', done: 'Done',
    search: 'Search', loading: 'Loading...', listenAgain: '🔊 Listen Again',
    medicineCheckerTitle: 'AI Symptom Checker', medicineCheckerDesc: 'Describe your symptoms using voice or text',
    medicineReminderTitle: 'Medicine Reminder', medicineReminderDesc: 'Never miss your medicines again',
    healthLockerTitle: 'Digital Health Locker', healthLockerDesc: 'Store your health records safely',
    emergencyTitle: 'Emergency', emergencyDesc: 'Quick access to emergency services',
    voiceAssistantTitle: 'Voice Assistant', voiceAssistantDesc: 'Speak to get healthcare guidance',
    nearbyDoctorsTitle: 'Nearby Doctors', nearbyDoctorsDesc: 'Find doctors near your location',
    settingsTitle: 'Settings', settingsDesc: 'Customize your experience',
    darkMode: 'Dark Mode', lightMode: 'Light Mode', language: 'Language',
    voiceGuidance: 'Voice Guidance', fontSize: 'Font Size',
    ambulance: 'Ambulance', police: 'Police', fire: 'Fire Department',
    bloodGroup: 'Blood Group', allergies: 'Allergies', diseases: 'Medical Conditions',
    vaccinations: 'Vaccinations', reports: 'Medical Reports',
    medicineName: 'Medicine Name', dosage: 'Dosage', time: 'Time', date: 'Date',
    frequency: 'Frequency', taken: 'Mark as Taken', takenStatus: 'Taken',
    reasonForReminder: 'Reason for Reminder', tapMicForReason: 'Tap mic to record reason',
    timeRequired: 'Time is required to save this reminder.',
    selectDate: 'Select Date',
    sosButton: 'SOS Emergency', firstAid: 'First Aid',
    emergencyContacts: 'Emergency Contacts', addContact: 'Add Contact',
    name: 'Name', phone: 'Phone', relation: 'Relation',
    homeCare: 'Home Care', visitPHC: 'Visit Primary Health Centre',
    visitHospital: 'Visit District Hospital', seekEmergency: 'Seek Emergency Help',
    tapToSpeak: 'Tap to Speak', listening: 'Listening...', processing: 'Processing...', speakNow: 'Speak now...',
    offlineMode: 'Offline Mode', offlineMessage: 'You are offline. Data is saved locally.', backOnline: 'Back Online',
    noReminders: 'No medicine reminders added yet.', noRecords: 'No health records found.',
    addMedicine: 'Add Medicine', daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly',
    morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening', night: 'Night',
    symptomsPrompt: 'Describe your symptoms or answer the questions below.',
    doYouHave: 'Do you have', fever: 'fever', cough: 'cough',
    breathingDifficulty: 'breathing difficulty', chestPain: 'chest pain',
    headache: 'headache', vomiting: 'vomiting', diarrhea: 'diarrhea',
    bodyPain: 'body pain', soreThroat: 'sore throat', rash: 'skin rash',
    resultTitle: 'Health Recommendation',
    aboutTitle: 'About MediVerse', aboutDesc: 'MediVerse is an AI-powered healthcare application built for rural communities.',
    version: 'Version 1.0.0', madeWith: 'Made with ❤️ for rural healthcare',
    searchDoctors: 'Search Doctors', searchPlaceholder: 'Search by city, village, pincode or specialization...',
    useMyLocation: 'Use My Location', availableNow: 'Available Now', unavailable: 'Unavailable',
    getDirections: 'Get Directions', callDoctor: 'Call Doctor', kmAway: 'km away',
    experience: 'Experience', noResults: 'No doctors found. Try a different city, pincode or specialization.',
    offlineDoctors: 'Showing previously searched results (offline mode)',
    uploadFile: 'Upload File', uploadedFiles: 'Uploaded Files',
    fileType: 'File Type', fileSize: 'File Size', uploadDate: 'Upload Date',
    view: 'View', download: 'Download', noFilesUploaded: 'No files uploaded yet.',
    fileTooLarge: 'File too large. Maximum size allowed is 2 MB.',
  },

  // ── KANNADA ────────────────────────────────────────────────────────────────
  kn: {
    appName: 'ಮೆಡಿವರ್ಸ್', tagline: 'ಎಲ್ಲರಿಗೂ ಸ್ಮಾರ್ಟ್ ಆರೋಗ್ಯ ಸೇವೆ',
    home: 'ಮನೆ', symptomChecker: 'ರೋಗಲಕ್ಷಣ ಪರೀಕ್ಷೆ', medicineReminder: 'ಔಷಧ ಜ್ಞಾಪನೆ',
    healthLocker: 'ಆರೋಗ್ಯ ಲಾಕರ್', emergency: 'ತುರ್ತು ಸಹಾಯ', settings: 'ಸೆಟ್ಟಿಂಗ್ಸ್',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ', nearbyDoctors: 'ಸಮೀಪದ ವೈದ್ಯರು',
    welcome: 'ಮೆಡಿವರ್ಸ್‌ಗೆ ಸ್ವಾಗತ', welcomeSubtitle: 'ಗ್ರಾಮೀಣ ಸಮುದಾಯಗಳಿಗಾಗಿ AI ಆರೋಗ್ಯ ಸಹಾಯಕ',
    startVoice: 'ಧ್ವನಿ ಸಹಾಯಕ ಪ್ರಾರಂಭಿಸಿ', checkSymptoms: 'ರೋಗಲಕ್ಷಣ ಪರೀಕ್ಷಿಸಿ',
    addReminder: 'ಜ್ಞಾಪನೆ ಸೇರಿಸಿ', viewRecords: 'ದಾಖಲೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ', callHelp: 'ಸಹಾಯಕ್ಕಾಗಿ ಕರೆ ಮಾಡಿ',
    online: 'ಆನ್‌ಲೈನ್', offline: 'ಆಫ್‌ಲೈನ್', syncPending: 'ಸಿಂಕ್ ಬಾಕಿ',
    save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', edit: 'ಸಂಪಾದಿಸಿ', delete: 'ಅಳಿಸಿ', add: 'ಸೇರಿಸಿ',
    yes: 'ಹೌದು', no: 'ಇಲ್ಲ', next: 'ಮುಂದೆ', back: 'ಹಿಂದೆ', done: 'ಮುಗಿಯಿತು',
    search: 'ಹುಡುಕಿ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', listenAgain: '🔊 ಮತ್ತೆ ಕೇಳಿ',
    medicineCheckerTitle: 'AI ರೋಗಲಕ್ಷಣ ಪರೀಕ್ಷಕ', medicineCheckerDesc: 'ಧ್ವನಿ ಅಥವಾ ಪಠ್ಯ ಮೂಲಕ ರೋಗಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ',
    medicineReminderTitle: 'ಔಷಧ ಜ್ಞಾಪನೆ', medicineReminderDesc: 'ಇನ್ನು ಮೇಲೆ ಔಷಧ ತೆಗೆದುಕೊಳ್ಳಲು ಮರೆಯಬೇಡಿ',
    healthLockerTitle: 'ಡಿಜಿಟಲ್ ಆರೋಗ್ಯ ಲಾಕರ್', healthLockerDesc: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ದಾಖಲೆಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸಂಗ್ರಹಿಸಿ',
    emergencyTitle: 'ತುರ್ತು ಸಹಾಯ', emergencyDesc: 'ತುರ್ತು ಸೇವೆಗಳಿಗೆ ತ್ವರಿತ ಪ್ರವೇಶ',
    nearbyDoctorsTitle: 'ಸಮೀಪದ ವೈದ್ಯರು', nearbyDoctorsDesc: 'ನಿಮ್ಮ ಸ್ಥಳದ ಬಳಿ ವೈದ್ಯರನ್ನು ಹುಡುಕಿ',
    voiceAssistantTitle: 'ಧ್ವನಿ ಸಹಾಯಕ', voiceAssistantDesc: 'ಆರೋಗ್ಯ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಲು ಮಾತನಾಡಿ',
    settingsTitle: 'ಸೆಟ್ಟಿಂಗ್ಸ್', settingsDesc: 'ನಿಮ್ಮ ಅನುಭವವನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್', lightMode: 'ಲೈಟ್ ಮೋಡ್', language: 'ಭಾಷೆ',
    voiceGuidance: 'ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನ', fontSize: 'ಅಕ್ಷರ ಗಾತ್ರ',
    ambulance: 'ಆಂಬ್ಯುಲೆನ್ಸ್', police: 'ಪೊಲೀಸ್', fire: 'ಅಗ್ನಿಶಾಮಕ',
    bloodGroup: 'ರಕ್ತ ಗುಂಪು', allergies: 'ಅಲರ್ಜಿಗಳು', diseases: 'ವೈದ್ಯಕೀಯ ಸ್ಥಿತಿಗಳು',
    vaccinations: 'ಲಸಿಕೆಗಳು', reports: 'ವೈದ್ಯಕೀಯ ವರದಿಗಳು',
    medicineName: 'ಔಷಧ ಹೆಸರು', dosage: 'ಡೋಸ್', time: 'ಸಮಯ', date: 'ದಿನಾಂಕ',
    frequency: 'ಆವರ್ತನ', taken: 'ತೆಗೆದುಕೊಂಡಿದ್ದೇನೆ', takenStatus: 'ತೆಗೆದುಕೊಂಡಿದ್ದೇನೆ',
    reasonForReminder: 'ಜ್ಞಾಪನೆಯ ಕಾರಣ', tapMicForReason: 'ಕಾರಣವನ್ನು ಧ್ವನಿ ಮೂಲಕ ದಾಖಲಿಸಲು ಮೈಕ್ ಒತ್ತಿ',
    timeRequired: 'ಈ ಜ್ಞಾಪನೆಯನ್ನು ಉಳಿಸಲು ಸಮಯ ಅಗತ್ಯ.',
    selectDate: 'ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ',
    sosButton: 'SOS ತುರ್ತು', firstAid: 'ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ',
    emergencyContacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು', addContact: 'ಸಂಪರ್ಕ ಸೇರಿಸಿ',
    name: 'ಹೆಸರು', phone: 'ಫೋನ್', relation: 'ಸಂಬಂಧ',
    homeCare: 'ಮನೆ ಆರೈಕೆ', visitPHC: 'ಪ್ರಾಥಮಿಕ ಆರೋಗ್ಯ ಕೇಂದ್ರಕ್ಕೆ ಭೇಟಿ ಕೊಡಿ',
    visitHospital: 'ಜಿಲ್ಲಾ ಆಸ್ಪತ್ರೆಗೆ ಭೇಟಿ ಕೊಡಿ', seekEmergency: 'ತಕ್ಷಣ ತುರ್ತು ಸಹಾಯ ಪಡೆಯಿರಿ',
    tapToSpeak: 'ಮಾತನಾಡಲು ಒತ್ತಿ', listening: 'ಕೇಳುತ್ತಿದ್ದೇನೆ...', processing: 'ಪ್ರಕ್ರಿಯೆ ನಡೆಯುತ್ತಿದೆ...', speakNow: 'ಈಗ ಮಾತನಾಡಿ...',
    offlineMode: 'ಆಫ್‌ಲೈನ್ ಮೋಡ್', offlineMessage: 'ನೀವು ಆಫ್‌ಲೈನ್ ಆಗಿದ್ದೀರಿ. ಡೇಟಾ ಸ್ಥಳೀಯವಾಗಿ ಉಳಿಸಲಾಗಿದೆ.', backOnline: 'ಆನ್‌ಲೈನ್‌ಗೆ ಹಿಂದಿರುಗಿದ್ದೇವೆ',
    noReminders: 'ಯಾವುದೇ ಔಷಧ ಜ್ಞಾಪನೆ ಸೇರಿಸಲಾಗಿಲ್ಲ.', noRecords: 'ಯಾವುದೇ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    addMedicine: 'ಔಷಧ ಸೇರಿಸಿ', daily: 'ದೈನಂದಿನ', weekly: 'ವಾರಕ್ಕೊಮ್ಮೆ', monthly: 'ತಿಂಗಳಿಗೊಮ್ಮೆ',
    morning: 'ಬೆಳಗ್ಗೆ', afternoon: 'ಮಧ್ಯಾಹ್ನ', evening: 'ಸಂಜೆ', night: 'ರಾತ್ರಿ',
    symptomsPrompt: 'ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ ಅಥವಾ ಕೆಳಗಿನ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ.',
    doYouHave: 'ನಿಮಗೆ ಇದೆಯೇ', fever: 'ಜ್ವರ', cough: 'ಕೆಮ್ಮು',
    breathingDifficulty: 'ಉಸಿರಾಟದ ತೊಂದರೆ', chestPain: 'ಎದೆ ನೋವು',
    headache: 'ತಲೆನೋವು', vomiting: 'ವಾಂತಿ', diarrhea: 'ಭೇದಿ',
    bodyPain: 'ಮೈ ನೋವು', soreThroat: 'ಗಂಟಲು ನೋವು', rash: 'ಚರ್ಮದ ದದ್ದು',
    resultTitle: 'ಆರೋಗ್ಯ ಶಿಫಾರಸು',
    aboutTitle: 'ಮೆಡಿವರ್ಸ್ ಬಗ್ಗೆ', aboutDesc: 'ಮೆಡಿವರ್ಸ್ ಗ್ರಾಮೀಣ ಸಮುದಾಯಗಳಿಗಾಗಿ ನಿರ್ಮಿಸಲಾದ AI ಆರೋಗ್ಯ ಅಪ್ಲಿಕೇಶನ್.',
    version: 'ಆವೃತ್ತಿ 1.0.0', madeWith: 'ಗ್ರಾಮೀಣ ಆರೋಗ್ಯಕ್ಕಾಗಿ ❤️ ನಿಂದ ತಯಾರಿಸಲಾಗಿದೆ',
    searchDoctors: 'ವೈದ್ಯರನ್ನು ಹುಡುಕಿ', searchPlaceholder: 'ನಗರ, ಗ್ರಾಮ, ಪಿನ್‌ಕೋಡ್ ಅಥವಾ ವಿಶೇಷತೆಯಿಂದ ಹುಡುಕಿ...',
    useMyLocation: 'ನನ್ನ ಸ್ಥಳ ಬಳಸಿ', availableNow: 'ಈಗ ಲಭ್ಯ', unavailable: 'ಲಭ್ಯವಿಲ್ಲ',
    getDirections: 'ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ', callDoctor: 'ವೈದ್ಯರಿಗೆ ಕರೆ ಮಾಡಿ', kmAway: 'ಕಿ.ಮೀ ದೂರದಲ್ಲಿ',
    experience: 'ಅನುಭವ', noResults: 'ಯಾವುದೇ ವೈದ್ಯರು ಕಂಡುಬಂದಿಲ್ಲ.',
    offlineDoctors: 'ಹಿಂದೆ ಹುಡುಕಿದ ಫಲಿತಾಂಶಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ (ಆಫ್‌ಲೈನ್)',
    uploadFile: 'ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', uploadedFiles: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಫೈಲ್‌ಗಳು',
    fileType: 'ಫೈಲ್ ಪ್ರಕಾರ', fileSize: 'ಫೈಲ್ ಗಾತ್ರ', uploadDate: 'ಅಪ್‌ಲೋಡ್ ದಿನಾಂಕ',
    view: 'ವೀಕ್ಷಿಸಿ', download: 'ಡೌನ್‌ಲೋಡ್', noFilesUploaded: 'ಇನ್ನೂ ಯಾವುದೇ ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿಲ್ಲ.',
    fileTooLarge: 'ಫೈಲ್ ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ. ಗರಿಷ್ಠ 2MB ಮಾತ್ರ.',
  },

  // ── HINDI ──────────────────────────────────────────────────────────────────
  hi: {
    appName: 'मेडीवर्स', tagline: 'सभी के लिए स्मार्ट स्वास्थ्य सेवा',
    home: 'होम', symptomChecker: 'लक्षण जाँच', medicineReminder: 'दवा अनुस्मारक',
    healthLocker: 'स्वास्थ्य लॉकर', emergency: 'आपातकाल', settings: 'सेटिंग्स',
    about: 'हमारे बारे में', nearbyDoctors: 'नज़दीकी डॉक्टर',
    welcome: 'मेडीवर्स में आपका स्वागत है', welcomeSubtitle: 'ग्रामीण समुदायों के लिए AI स्वास्थ्य सहायक',
    startVoice: 'वॉयस असिस्टेंट शुरू करें', checkSymptoms: 'लक्षण जाँचें',
    addReminder: 'अनुस्मारक जोड़ें', viewRecords: 'रिकॉर्ड देखें', callHelp: 'मदद के लिए कॉल करें',
    online: 'ऑनलाइन', offline: 'ऑफलाइन', syncPending: 'सिंक बाकी',
    save: 'सहेजें', cancel: 'रद्द करें', edit: 'संपादित करें', delete: 'हटाएं', add: 'जोड़ें',
    yes: 'हाँ', no: 'नहीं', next: 'अगला', back: 'पीछे', done: 'हो गया',
    search: 'खोजें', loading: 'लोड हो रहा है...', listenAgain: '🔊 फिर सुनें',
    medicineCheckerTitle: 'AI लक्षण जाँचकर्ता', medicineCheckerDesc: 'आवाज़ या टेक्स्ट से लक्षण बताएं',
    medicineReminderTitle: 'दवा अनुस्मारक', medicineReminderDesc: 'दवा लेना कभी न भूलें',
    healthLockerTitle: 'डिजिटल स्वास्थ्य लॉकर', healthLockerDesc: 'अपने स्वास्थ्य रिकॉर्ड सुरक्षित रखें',
    emergencyTitle: 'आपातकाल', emergencyDesc: 'आपातकालीन सेवाओं तक त्वरित पहुँच',
    nearbyDoctorsTitle: 'नज़दीकी डॉक्टर', nearbyDoctorsDesc: 'अपने नज़दीक डॉक्टर खोजें',
    voiceAssistantTitle: 'वॉयस असिस्टेंट', voiceAssistantDesc: 'स्वास्थ्य मार्गदर्शन के लिए बोलें',
    settingsTitle: 'सेटिंग्स', settingsDesc: 'अपना अनुभव अनुकूलित करें',
    darkMode: 'डार्क मोड', lightMode: 'लाइट मोड', language: 'भाषा',
    voiceGuidance: 'वॉयस गाइडेंस', fontSize: 'फ़ॉन्ट आकार',
    ambulance: 'एम्बुलेंस', police: 'पुलिस', fire: 'अग्निशमन विभाग',
    bloodGroup: 'रक्त समूह', allergies: 'एलर्जी', diseases: 'चिकित्सा स्थितियाँ',
    vaccinations: 'टीकाकरण', reports: 'चिकित्सा रिपोर्ट',
    medicineName: 'दवा का नाम', dosage: 'खुराक', time: 'समय', date: 'तारीख',
    frequency: 'आवृत्ति', taken: 'ले लिया', takenStatus: 'ले लिया',
    reasonForReminder: 'अनुस्मारक का कारण', tapMicForReason: 'आवाज़ से कारण दर्ज करने के लिए माइक दबाएं',
    timeRequired: 'इस अनुस्मारक को सहेजने के लिए समय आवश्यक है।',
    selectDate: 'तारीख चुनें',
    sosButton: 'SOS आपातकाल', firstAid: 'प्राथमिक चिकित्सा',
    emergencyContacts: 'आपातकालीन संपर्क', addContact: 'संपर्क जोड़ें',
    name: 'नाम', phone: 'फ़ोन', relation: 'संबंध',
    homeCare: 'घर पर देखभाल', visitPHC: 'प्राथमिक स्वास्थ्य केंद्र जाएं',
    visitHospital: 'जिला अस्पताल जाएं', seekEmergency: 'तुरंत आपातकालीन मदद लें',
    tapToSpeak: 'बोलने के लिए टैप करें', listening: 'सुन रहा हूँ...', processing: 'प्रक्रिया हो रही है...', speakNow: 'अभी बोलें...',
    offlineMode: 'ऑफलाइन मोड', offlineMessage: 'आप ऑफलाइन हैं। डेटा स्थानीय रूप से सहेजा गया है।', backOnline: 'वापस ऑनलाइन',
    noReminders: 'अभी तक कोई दवा अनुस्मारक नहीं जोड़ा गया।', noRecords: 'कोई स्वास्थ्य रिकॉर्ड नहीं मिला।',
    addMedicine: 'दवा जोड़ें', daily: 'दैनिक', weekly: 'साप्ताहिक', monthly: 'मासिक',
    morning: 'सुबह', afternoon: 'दोपहर', evening: 'शाम', night: 'रात',
    symptomsPrompt: 'अपने लक्षण बताएं या नीचे दिए प्रश्नों का उत्तर दें।',
    doYouHave: 'क्या आपको', fever: 'बुखार है', cough: 'खांसी है',
    breathingDifficulty: 'सांस लेने में कठिनाई है', chestPain: 'सीने में दर्द है',
    headache: 'सिरदर्द है', vomiting: 'उल्टी हो रही है', diarrhea: 'दस्त हैं',
    bodyPain: 'शरीर में दर्द है', soreThroat: 'गले में खराश है', rash: 'त्वचा पर चकत्ते हैं',
    resultTitle: 'स्वास्थ्य अनुशंसा',
    aboutTitle: 'मेडीवर्स के बारे में', aboutDesc: 'मेडीवर्स ग्रामीण समुदायों के लिए बनाया गया AI स्वास्थ्य ऐप है।',
    version: 'संस्करण 1.0.0', madeWith: 'ग्रामीण स्वास्थ्य के लिए ❤️ से बनाया गया',
    searchDoctors: 'डॉक्टर खोजें', searchPlaceholder: 'शहर, गाँव, पिनकोड या विशेषज्ञता से खोजें...',
    useMyLocation: 'मेरी लोकेशन उपयोग करें', availableNow: 'अभी उपलब्ध', unavailable: 'अनुपलब्ध',
    getDirections: 'दिशा-निर्देश', callDoctor: 'डॉक्टर को कॉल करें', kmAway: 'किमी दूर',
    experience: 'अनुभव', noResults: 'कोई डॉक्टर नहीं मिला। कोई अलग खोज आज़माएं।',
    offlineDoctors: 'पहले खोजे गए परिणाम दिखाए जा रहे हैं (ऑफलाइन)',
    uploadFile: 'फ़ाइल अपलोड करें', uploadedFiles: 'अपलोड की गई फ़ाइलें',
    fileType: 'फ़ाइल प्रकार', fileSize: 'फ़ाइल आकार', uploadDate: 'अपलोड तारीख',
    view: 'देखें', download: 'डाउनलोड', noFilesUploaded: 'अभी तक कोई फ़ाइल अपलोड नहीं हुई।',
    fileTooLarge: 'फ़ाइल बहुत बड़ी है। अधिकतम 2MB अनुमत है।',
  },

  // ── TAMIL ──────────────────────────────────────────────────────────────────
  ta: {
    appName: 'மெடிவர்ஸ்', tagline: 'அனைவருக்கும் ஸ்மார்ட் சுகாதாரம்',
    home: 'முகப்பு', symptomChecker: 'அறிகுறி சரிபார்ப்பு', medicineReminder: 'மருந்து நினைவூட்டல்',
    healthLocker: 'சுகாதார லாக்கர்', emergency: 'அவசரநிலை', settings: 'அமைப்புகள்',
    about: 'எங்களைப் பற்றி', nearbyDoctors: 'அருகிலுள்ள மருத்துவர்கள்',
    welcome: 'மெடிவர்ஸ்-ல் வரவேற்கிறோம்', welcomeSubtitle: 'கிராமப்புற சமூகங்களுக்கான AI சுகாதார துணையி',
    startVoice: 'குரல் உதவியாளரை தொடங்கு', checkSymptoms: 'அறிகுறிகளை சரிபார்',
    addReminder: 'நினைவூட்டல் சேர்', viewRecords: 'பதிவுகளை காண்', callHelp: 'உதவிக்கு அழை',
    online: 'ஆன்லைன்', offline: 'ஆஃப்லைன்', syncPending: 'ஒத்திசைவு நிலுவையில்',
    save: 'சேமி', cancel: 'ரத்துசெய்', edit: 'திருத்து', delete: 'நீக்கு', add: 'சேர்',
    yes: 'ஆம்', no: 'இல்லை', next: 'அடுத்து', back: 'பின்', done: 'முடிந்தது',
    search: 'தேடு', loading: 'ஏற்றுகிறது...', listenAgain: '🔊 மீண்டும் கேள்',
    medicineCheckerTitle: 'AI அறிகுறி சரிபார்ப்பாளர்',
    nearbyDoctorsTitle: 'அருகிலுள்ள மருத்துவர்கள்', nearbyDoctorsDesc: 'உங்கள் இடத்திற்கு அருகில் மருத்துவர்களை தேடுங்கள்',
    settingsTitle: 'அமைப்புகள்', settingsDesc: 'உங்கள் அனுபவத்தை தனிப்பயனாக்கு',
    darkMode: 'இருண்ட பயன்முறை', lightMode: 'ஒளி பயன்முறை', language: 'மொழி',
    ambulance: 'ஆம்புலன்ஸ்', police: 'காவல்துறை', fire: 'தீயணைப்பு',
    bloodGroup: 'இரத்த வகை', allergies: 'ஒவ்வாமைகள்', diseases: 'மருத்துவ நிலைகள்',
    vaccinations: 'தடுப்பூசிகள்', reports: 'மருத்துவ அறிக்கைகள்',
    medicineName: 'மருந்து பெயர்', dosage: 'அளவு', time: 'நேரம்', date: 'தேதி',
    frequency: 'அலைவீச்சு', taken: 'எடுத்தாயிற்று', takenStatus: 'எடுத்தாயிற்று',
    reasonForReminder: 'நினைவூட்டலுக்கான காரணம்', tapMicForReason: 'குரல் மூலம் காரணம் பதிவு செய்ய மைக்கை தொடு',
    timeRequired: 'இந்த நினைவூட்டலை சேமிக்க நேரம் தேவை.',
    selectDate: 'தேதி தேர்ந்தெடு', sosButton: 'SOS அவசரநிலை',
    firstAid: 'முதலுதவி', emergencyContacts: 'அவசர தொடர்புகள்',
    name: 'பெயர்', phone: 'தொலைபேசி', relation: 'உறவு',
    homeCare: 'வீட்டு பராமரிப்பு', visitPHC: 'ஆரம்ப சுகாதார நிலையம் செல்', visitHospital: 'மாவட்ட மருத்துவமனை செல்',
    tapToSpeak: 'பேச தொடு', listening: 'கேட்கிறேன்...', listenAgain: '🔊 மீண்டும் கேள்',
    noReminders: 'இன்னும் மருந்து நினைவூட்டல் சேர்க்கப்படவில்லை.', addMedicine: 'மருந்து சேர்',
    daily: 'தினசரி', weekly: 'வாராந்திர', monthly: 'மாதாந்திர',
    morning: 'காலை', afternoon: 'மதியம்', evening: 'மாலை', night: 'இரவு',
    doYouHave: 'உங்களுக்கு உள்ளதா', fever: 'காய்ச்சல்', cough: 'இருமல்',
    breathingDifficulty: 'சுவாசிக்க சிரமம்', chestPain: 'நெஞ்சு வலி',
    headache: 'தலைவலி', vomiting: 'வாந்தி', diarrhea: 'வயிற்றுப்போக்கு',
    bodyPain: 'உடல் வலி', soreThroat: 'தொண்டை வலி', rash: 'தோல் தடிப்பு',
    searchDoctors: 'மருத்துவர்களை தேடு', searchPlaceholder: 'நகரம், கிராமம், பின்கோட் அல்லது நிபுணத்துவம் மூலம் தேடு...',
    useMyLocation: 'என் இடத்தை பயன்படுத்து', availableNow: 'இப்போது கிடைக்கும்', unavailable: 'கிடைக்கவில்லை',
    getDirections: 'வழிகாட்டி', callDoctor: 'மருத்துவரை அழை', kmAway: 'கி.மீ தூரம்',
    noResults: 'மருத்துவர்கள் கிடைக்கவில்லை. வேறு தேடலை முயற்சிக்கவும்.',
    uploadFile: 'கோப்பு பதிவேற்று', view: 'காண்', download: 'பதிவிறக்கு',
    noFilesUploaded: 'இன்னும் கோப்புகள் பதிவேற்றப்படவில்லை.',
    version: 'பதிப்பு 1.0.0', madeWith: 'கிராம சுகாதாரத்திற்கு ❤️ உடன் உருவாக்கப்பட்டது',
  },

  // ── TELUGU ─────────────────────────────────────────────────────────────────
  te: {
    appName: 'మెడివర్స్', tagline: 'అందరికీ స్మార్ట్ ఆరోగ్యం',
    home: 'హోమ్', symptomChecker: 'లక్షణాల తనిఖీ', medicineReminder: 'మందు రిమైండర్',
    healthLocker: 'ఆరోగ్య లాకర్', emergency: 'అత్యవసర', settings: 'సెట్టింగ్‌లు',
    about: 'మా గురించి', nearbyDoctors: 'సమీప వైద్యులు',
    welcome: 'మెడివర్స్‌కు స్వాగతం', welcomeSubtitle: 'గ్రామీణ సమాజాలకు AI ఆరోగ్య సహాయకుడు',
    startVoice: 'వాయిస్ అసిస్టెంట్ ప్రారంభించు', checkSymptoms: 'లక్షణాలు తనిఖీ చేయి',
    save: 'సేవ్ చేయి', cancel: 'రద్దు చేయి', edit: 'సవరించు', delete: 'తొలగించు', add: 'జోడించు',
    yes: 'అవును', no: 'కాదు', search: 'వెతుకు', loading: 'లోడ్ అవుతోంది...',
    listenAgain: '🔊 మళ్ళీ వినండి',
    nearbyDoctorsTitle: 'సమీప వైద్యులు', nearbyDoctorsDesc: 'మీ స్థానానికి సమీపంలో వైద్యులను కనుగొనండి',
    ambulance: 'అంబులెన్స్', police: 'పోలీసు', fire: 'అగ్నిమాపక విభాగం',
    bloodGroup: 'రక్త సమూహం', medicineName: 'మందు పేరు', dosage: 'మోతాదు', time: 'సమయం', date: 'తేదీ',
    frequency: 'పౌనఃపున్యం', taken: 'తీసుకున్నాను', morning: 'ఉదయం', afternoon: 'మధ్యాహ్నం', evening: 'సాయంత్రం', night: 'రాత్రి',
    daily: 'రోజూ', weekly: 'వారంవారం', monthly: 'నెలకొకసారి',
    fever: 'జ్వరం', cough: 'దగ్గు', headache: 'తలనొప్పి', bodyPain: 'శరీర నొప్పి',
    doYouHave: 'మీకు ఉందా', reasonForReminder: 'రిమైండర్ కారణం', timeRequired: 'ఈ రిమైండర్ సేవ్ చేయడానికి సమయం అవసరం.',
    searchDoctors: 'వైద్యులు వెతుకు', availableNow: 'ఇప్పుడు అందుబాటులో', unavailable: 'అందుబాటులో లేదు',
    getDirections: 'దిశలు', callDoctor: 'వైద్యుడిని పిలవండి', noResults: 'వైద్యులు కనుగొనబడలేదు.',
    uploadFile: 'ఫైల్ అప్‌లోడ్', view: 'చూడు', download: 'డౌన్లోడ్', noFilesUploaded: 'ఇంకా ఫైళ్ళు అప్‌లోడ్ కాలేదు.',
    version: 'వెర్షన్ 1.0.0', madeWith: 'గ్రామీణ ఆరోగ్యం కోసం ❤️ తో నిర్మించబడింది',
  },

  // ── MALAYALAM ──────────────────────────────────────────────────────────────
  ml: {
    appName: 'മെഡിവേഴ്സ്', tagline: 'എല്ലാവർക്കും സ്മാർട്ട് ആരോഗ്യ സേവനം',
    home: 'ഹോം', symptomChecker: 'ലക്ഷണ പരിശോധന', medicineReminder: 'മരുന്ന് ഓർമ്മപ്പെടുത്തൽ',
    healthLocker: 'ആരോഗ്യ ലോക്കർ', emergency: 'അടിയന്തിരം', settings: 'ക്രമീകരണങ്ങൾ',
    about: 'ഞങ്ങളെക്കുറിച്ച്', nearbyDoctors: 'അടുത്തുള്ള ഡോക്ടർ',
    welcome: 'മെഡിവേഴ്സിലേക്ക് സ്വാഗതം', welcomeSubtitle: 'ഗ്രാമീണ സമൂഹങ്ങൾക്കുള്ള AI ആരോഗ്യ സഹായി',
    save: 'സേവ് ചെയ്യുക', cancel: 'റദ്ദാക്കുക', edit: 'തിരുത്തുക', delete: 'ഇല്ലാതാക്കുക', add: 'ചേർക്കുക',
    yes: 'അതെ', no: 'ഇല്ല', search: 'തിരയുക', loading: 'ലോഡ് ചെയ്യുന്നു...', listenAgain: '🔊 വീണ്ടും കേൾക്കുക',
    nearbyDoctorsTitle: 'അടുത്തുള്ള ഡോക്ടർ', nearbyDoctorsDesc: 'നിങ്ങളുടെ സ്ഥലത്തിനടുത്ത് ഡോക്ടർമാരെ കണ്ടെത്തുക',
    ambulance: 'ആംബുലൻസ്', police: 'പോലീസ്', fire: 'അഗ്നിശമന വിഭാഗം',
    bloodGroup: 'രക്ത ഗ്രൂപ്പ്', medicineName: 'മരുന്നിന്റെ പേര്', dosage: 'ഡോസ്', time: 'സമയം', date: 'തീയതി',
    frequency: 'ആവൃത്തി', morning: 'രാവിലെ', afternoon: 'ഉച്ചയ്ക്ക്', evening: 'വൈകുന്നേരം', night: 'രാത്രി',
    daily: 'ദൈനംദിനം', weekly: 'ആഴ്ചതോറും', monthly: 'മാസംതോറും',
    fever: 'പനി', cough: 'ചുമ', headache: 'തലവേദന', bodyPain: 'ശരീര വേദന',
    reasonForReminder: 'ഓർമ്മപ്പെടുത്തലിന്റെ കാരണം', timeRequired: 'ഈ ഓർമ്മപ്പെടുത്തൽ സേവ് ചെയ്യാൻ സമയം ആവശ്യമാണ്.',
    availableNow: 'ഇപ്പോൾ ലഭ്യം', unavailable: 'ലഭ്യമല്ല', getDirections: 'ദിശകൾ', callDoctor: 'ഡോക്ടറെ വിളിക്കുക',
    noResults: 'ഡോക്ടർമാർ കണ്ടെത്തിയില്ല.', searchDoctors: 'ഡോക്ടർമാരെ തിരയുക',
    uploadFile: 'ഫയൽ അപ്‌ലോഡ് ചെയ്യുക', view: 'കാണുക', download: 'ഡൗൺലോഡ്',
    noFilesUploaded: 'ഇതുവരെ ഫയലുകൾ അപ്‌ലോഡ് ചെയ്തിട്ടില്ല.',
    version: 'പതിപ്പ് 1.0.0', madeWith: 'ഗ്രാമീണ ആരോഗ്യത്തിനായി ❤️ കൊണ്ട് നിർമ്മിച്ചത്',
  },

  // ── MARATHI ────────────────────────────────────────────────────────────────
  mr: {
    appName: 'मेडीवर्स', tagline: 'सर्वांसाठी स्मार्ट आरोग्य सेवा',
    home: 'मुखपृष्ठ', symptomChecker: 'लक्षण तपासणी', medicineReminder: 'औषध स्मरणपत्र',
    healthLocker: 'आरोग्य लॉकर', emergency: 'आपत्कालीन', settings: 'सेटिंग्ज',
    about: 'आमच्याबद्दल', nearbyDoctors: 'जवळील डॉक्टर',
    welcome: 'मेडीवर्समध्ये स्वागत आहे', welcomeSubtitle: 'ग्रामीण समुदायांसाठी AI आरोग्य साथीदार',
    save: 'जतन करा', cancel: 'रद्द करा', edit: 'संपादित करा', delete: 'हटवा', add: 'जोडा',
    yes: 'हो', no: 'नाही', search: 'शोधा', loading: 'लोड होत आहे...', listenAgain: '🔊 पुन्हा ऐका',
    nearbyDoctorsTitle: 'जवळील डॉक्टर', nearbyDoctorsDesc: 'तुमच्या ठिकाणाजवळ डॉक्टर शोधा',
    ambulance: 'रुग्णवाहिका', police: 'पोलीस', fire: 'अग्निशमन विभाग',
    bloodGroup: 'रक्त गट', medicineName: 'औषधाचे नाव', dosage: 'मात्रा', time: 'वेळ', date: 'तारीख',
    frequency: 'वारंवारता', morning: 'सकाळ', afternoon: 'दुपार', evening: 'संध्याकाळ', night: 'रात्र',
    daily: 'दररोज', weekly: 'साप्ताहिक', monthly: 'मासिक',
    fever: 'ताप', cough: 'खोकला', headache: 'डोकेदुखी', bodyPain: 'अंगदुखी',
    reasonForReminder: 'स्मरणपत्राचे कारण', timeRequired: 'हे स्मरणपत्र जतन करण्यासाठी वेळ आवश्यक आहे.',
    availableNow: 'आता उपलब्ध', unavailable: 'उपलब्ध नाही', getDirections: 'दिशानिर्देश', callDoctor: 'डॉक्टरला कॉल करा',
    noResults: 'डॉक्टर सापडले नाहीत. वेगळी शोधणी करा.', searchDoctors: 'डॉक्टर शोधा',
    uploadFile: 'फाइल अपलोड करा', view: 'पाहा', download: 'डाउनलोड',
    noFilesUploaded: 'अद्याप कोणतीही फाइल अपलोड केलेली नाही.',
    version: 'आवृत्ती 1.0.0', madeWith: 'ग्रामीण आरोग्यासाठी ❤️ सह बनवले',
  },

  // ── BENGALI ────────────────────────────────────────────────────────────────
  bn: {
    appName: 'মেডিভার্স', tagline: 'সবার জন্য স্মার্ট স্বাস্থ্যসেবা',
    home: 'হোম', symptomChecker: 'উপসর্গ পরীক্ষক', medicineReminder: 'ওষুধ স্মরণিকা',
    healthLocker: 'স্বাস্থ্য লকার', emergency: 'জরুরি', settings: 'সেটিংস',
    about: 'আমাদের সম্পর্কে', nearbyDoctors: 'কাছের ডাক্তার',
    welcome: 'মেডিভার্সে স্বাগতম', welcomeSubtitle: 'গ্রামীণ সম্প্রদায়ের জন্য AI স্বাস্থ্য সহায়ক',
    save: 'সংরক্ষণ', cancel: 'বাতিল', edit: 'সম্পাদনা', delete: 'মুছুন', add: 'যোগ করুন',
    yes: 'হ্যাঁ', no: 'না', search: 'খুঁজুন', loading: 'লোড হচ্ছে...', listenAgain: '🔊 আবার শুনুন',
    nearbyDoctorsTitle: 'কাছের ডাক্তার', nearbyDoctorsDesc: 'আপনার কাছে ডাক্তার খুঁজুন',
    ambulance: 'অ্যাম্বুলেন্স', police: 'পুলিশ', fire: 'দমকল বিভাগ',
    bloodGroup: 'রক্তের গ্রুপ', medicineName: 'ওষুধের নাম', dosage: 'মাত্রা', time: 'সময়', date: 'তারিখ',
    morning: 'সকাল', afternoon: 'দুপুর', evening: 'বিকেল', night: 'রাত',
    daily: 'দৈনিক', weekly: 'সাপ্তাহিক', monthly: 'মাসিক',
    fever: 'জ্বর', cough: 'কাশি', headache: 'মাথাব্যথা', bodyPain: 'শরীর ব্যথা',
    reasonForReminder: 'স্মরণিকার কারণ', timeRequired: 'এই স্মরণিকা সংরক্ষণ করতে সময় প্রয়োজন।',
    availableNow: 'এখন পাওয়া যাচ্ছে', unavailable: 'পাওয়া যাচ্ছে না', getDirections: 'দিকনির্দেশ', callDoctor: 'ডাক্তার ডাকুন',
    noResults: 'কোনো ডাক্তার পাওয়া যায়নি।', searchDoctors: 'ডাক্তার খুঁজুন',
    uploadFile: 'ফাইল আপলোড', view: 'দেখুন', download: 'ডাউনলোড',
    noFilesUploaded: 'এখনো কোনো ফাইল আপলোড করা হয়নি।',
    version: 'সংস্করণ 1.0.0', madeWith: 'গ্রামীণ স্বাস্থ্যের জন্য ❤️ দিয়ে তৈরি',
  },

  // ── GUJARATI ───────────────────────────────────────────────────────────────
  gu: {
    appName: 'મેડિવર્સ', tagline: 'સૌ માટે સ્માર્ટ આરોગ્ય સેવા',
    home: 'હોમ', symptomChecker: 'લક્ષણ તપાસ', medicineReminder: 'દવા રિમાઇન્ડર',
    healthLocker: 'આરોગ્ય લૉકર', emergency: 'ઈમર્જન્સી', settings: 'સેટિંગ્સ',
    about: 'અમારા વિશે', nearbyDoctors: 'નજીકના ડૉક્ટર',
    welcome: 'મેડિવર્સમાં આપનું સ્વાગત છે', welcomeSubtitle: 'ગ્રામીણ સમુદાયો માટે AI સ્વાસ્થ્ય સહાયક',
    save: 'સાચવો', cancel: 'રદ કરો', edit: 'સંપાદિત કરો', delete: 'કાઢો', add: 'ઉમેરો',
    yes: 'હા', no: 'ના', search: 'શોધો', loading: 'લોડ થઈ રહ્યું છે...', listenAgain: '🔊 ફરી સાંભળો',
    nearbyDoctorsTitle: 'નજીકના ડૉક્ટર', nearbyDoctorsDesc: 'તમારી નજીક ડૉક્ટર શોધો',
    ambulance: 'એમ્બ્યુલન્સ', police: 'પોલીસ', fire: 'અગ્નિશામક',
    bloodGroup: 'લોહીનો ગ્રૂપ', medicineName: 'દવાનું નામ', dosage: 'ડોઝ', time: 'સમય', date: 'તારીખ',
    morning: 'સવારે', afternoon: 'બપોરે', evening: 'સાંજે', night: 'રાત્રે',
    daily: 'દૈનિક', weekly: 'સાપ્તાહિક', monthly: 'માસિક',
    fever: 'તાવ', cough: 'ઉધરસ', headache: 'માથાનો દુખાવો',
    reasonForReminder: 'રિમાઇન્ડરનું કારણ', timeRequired: 'આ રિમાઇન્ડર સાચવવા સમય જરૂરી છે.',
    availableNow: 'હાલ ઉપલબ્ધ', unavailable: 'અનુપલબ્ધ', getDirections: 'દિશા', callDoctor: 'ડૉક્ટરને કૉલ',
    noResults: 'ડૉક્ટર મળ્યા નહીં.', searchDoctors: 'ડૉક્ટર શોધો',
    uploadFile: 'ફાઇલ અપલોડ', view: 'જુઓ', download: 'ડાઉનલોડ', noFilesUploaded: 'હજી કોઈ ફાઇલ અપલોડ નથી.',
    version: 'સંસ્કરણ 1.0.0', madeWith: 'ગ્રામીણ સ્વાસ્થ્ય માટે ❤️ સાથે બનાવ્યું',
  },

  // ── PUNJABI ────────────────────────────────────────────────────────────────
  pa: {
    appName: 'ਮੈਡੀਵਰਸ', tagline: 'ਸਭ ਲਈ ਸਮਾਰਟ ਸਿਹਤ ਸੇਵਾ',
    home: 'ਹੋਮ', symptomChecker: 'ਲੱਛਣ ਜਾਂਚ', medicineReminder: 'ਦਵਾਈ ਯਾਦਦਿਹਾਨੀ',
    healthLocker: 'ਸਿਹਤ ਲਾਕਰ', emergency: 'ਐਮਰਜੈਂਸੀ', settings: 'ਸੈਟਿੰਗਜ਼',
    about: 'ਸਾਡੇ ਬਾਰੇ', nearbyDoctors: 'ਨੇੜੇ ਦੇ ਡਾਕਟਰ',
    welcome: 'ਮੈਡੀਵਰਸ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ', welcomeSubtitle: 'ਪੇਂਡੂ ਭਾਈਚਾਰਿਆਂ ਲਈ AI ਸਿਹਤ ਸਹਾਇਕ',
    save: 'ਸੇਵ ਕਰੋ', cancel: 'ਰੱਦ ਕਰੋ', edit: 'ਸੰਪਾਦਿਤ ਕਰੋ', delete: 'ਮਿਟਾਓ', add: 'ਜੋੜੋ',
    yes: 'ਹਾਂ', no: 'ਨਹੀਂ', search: 'ਖੋਜੋ', loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...', listenAgain: '🔊 ਦੁਬਾਰਾ ਸੁਣੋ',
    nearbyDoctorsTitle: 'ਨੇੜੇ ਦੇ ਡਾਕਟਰ', nearbyDoctorsDesc: 'ਆਪਣੇ ਨੇੜੇ ਡਾਕਟਰ ਲੱਭੋ',
    ambulance: 'ਐਂਬੂਲੈਂਸ', police: 'ਪੁਲਿਸ', fire: 'ਅੱਗ ਵਿਭਾਗ',
    bloodGroup: 'ਖੂਨ ਦਾ ਗਰੁੱਪ', medicineName: 'ਦਵਾਈ ਦਾ ਨਾਮ', dosage: 'ਖੁਰਾਕ', time: 'ਸਮਾਂ', date: 'ਤਾਰੀਖ',
    morning: 'ਸਵੇਰੇ', afternoon: 'ਦੁਪਹਿਰੇ', evening: 'ਸ਼ਾਮ', night: 'ਰਾਤ',
    daily: 'ਰੋਜ਼ਾਨਾ', weekly: 'ਹਫਤਾਵਾਰੀ', monthly: 'ਮਹੀਨੇਵਾਰ',
    fever: 'ਬੁਖ਼ਾਰ', cough: 'ਖੰਘ', headache: 'ਸਿਰ ਦਰਦ',
    reasonForReminder: 'ਯਾਦਦਿਹਾਨੀ ਦਾ ਕਾਰਨ', timeRequired: 'ਇਸ ਯਾਦਦਿਹਾਨੀ ਨੂੰ ਸੇਵ ਕਰਨ ਲਈ ਸਮਾਂ ਜ਼ਰੂਰੀ ਹੈ।',
    availableNow: 'ਹੁਣ ਉਪਲਬਧ', unavailable: 'ਉਪਲਬਧ ਨਹੀਂ', getDirections: 'ਦਿਸ਼ਾਵਾਂ', callDoctor: 'ਡਾਕਟਰ ਨੂੰ ਕਾਲ ਕਰੋ',
    noResults: 'ਕੋਈ ਡਾਕਟਰ ਨਹੀਂ ਮਿਲਿਆ।', searchDoctors: 'ਡਾਕਟਰ ਖੋਜੋ',
    uploadFile: 'ਫਾਇਲ ਅੱਪਲੋਡ', view: 'ਦੇਖੋ', download: 'ਡਾਊਨਲੋਡ', noFilesUploaded: 'ਅਜੇ ਕੋਈ ਫਾਇਲ ਅੱਪਲੋਡ ਨਹੀਂ।',
    version: 'ਸੰਸਕਰਣ 1.0.0', madeWith: 'ਪੇਂਡੂ ਸਿਹਤ ਲਈ ❤️ ਨਾਲ ਬਣਾਇਆ',
  },

  // ── URDU ───────────────────────────────────────────────────────────────────
  ur: {
    appName: 'میڈیورس', tagline: 'سب کے لیے سمارٹ صحت سروس',
    home: 'ہوم', symptomChecker: 'علامت جانچ', medicineReminder: 'دوائی یاددہانی',
    healthLocker: 'صحت لاکر', emergency: 'ایمرجنسی', settings: 'سیٹنگز',
    about: 'ہمارے بارے میں', nearbyDoctors: 'قریبی ڈاکٹر',
    welcome: 'میڈیورس میں خوش آمدید', welcomeSubtitle: 'دیہی برادریوں کے لیے AI صحت معاون',
    save: 'محفوظ کریں', cancel: 'منسوخ کریں', edit: 'ترمیم کریں', delete: 'حذف کریں', add: 'شامل کریں',
    yes: 'ہاں', no: 'نہیں', search: 'تلاش کریں', loading: 'لوڈ ہو رہا ہے...', listenAgain: '🔊 دوبارہ سنیں',
    nearbyDoctorsTitle: 'قریبی ڈاکٹر', nearbyDoctorsDesc: 'اپنے قریب ڈاکٹر تلاش کریں',
    ambulance: 'ایمبولینس', police: 'پولیس', fire: 'فائر بریگیڈ',
    bloodGroup: 'خون کا گروپ', medicineName: 'دوائی کا نام', dosage: 'خوراک', time: 'وقت', date: 'تاریخ',
    morning: 'صبح', afternoon: 'دوپہر', evening: 'شام', night: 'رات',
    daily: 'روزانہ', weekly: 'ہفتہ وار', monthly: 'ماہانہ',
    fever: 'بخار', cough: 'کھانسی', headache: 'سر درد',
    reasonForReminder: 'یاددہانی کی وجہ', timeRequired: 'اس یاددہانی کو محفوظ کرنے کے لیے وقت ضروری ہے۔',
    availableNow: 'ابھی دستیاب', unavailable: 'دستیاب نہیں', getDirections: 'رہنمائی', callDoctor: 'ڈاکٹر کو کال کریں',
    noResults: 'کوئی ڈاکٹر نہیں ملا۔', searchDoctors: 'ڈاکٹر تلاش کریں',
    uploadFile: 'فائل اپ لوڈ کریں', view: 'دیکھیں', download: 'ڈاؤنلوڈ', noFilesUploaded: 'ابھی تک کوئی فائل اپ لوڈ نہیں۔',
    version: 'ورژن 1.0.0', madeWith: 'دیہی صحت کے لیے ❤️ کے ساتھ بنایا گیا',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// TTS locale mapping — used by speechRecognition & textToSpeech services
// ─────────────────────────────────────────────────────────────────────────────
export const langToLocale = {
  en: 'en-IN', kn: 'kn-IN', hi: 'hi-IN', ta: 'ta-IN', te: 'te-IN',
  ml: 'ml-IN', mr: 'mr-IN', bn: 'bn-IN', gu: 'gu-IN', pa: 'pa-IN', ur: 'ur-PK',
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('mv_language') || 'en';
  });

  // Falls back to English for any missing key
  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('mv_language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, translations, langToLocale }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
